### ISSUE TITLE
Interpet flags interactively

### ISSUE THREAD

**Issue by Axlefublr** [mistweaverco/tafuta.nvim#1]
I've been looking for some way to use rg like I would in the shell - being able to pass in options and flags interactively, *along* with my search query (which would go as the last thing)
Would that be possible to make? Or, as an easier to implement alternative, being able to pass the options into the run function (as a string, would be my usecase, but it probably makes more sense to pass as table?)

**Comment by gorillamoe** [comment]
Thanks 🙏🏾 for coming up with this idea 💡! Will implement it.

**Comment by Axlefublr** [comment]
thank you so much! :3
